# Use the updated base image
FROM erc-mars-rover_base:latest

ARG ROS_DISTRO=humble
ARG BASE_FOLDER=/root/orin
ARG ROS_WORKSPACE_NAME=ERC-Mars-Rover

WORKDIR ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}

# Install build dependencies for OpenCV/TensorRT if needed
RUN apt-get update && \
    apt-get install -y \
        build-essential \
        cmake \
        git \
        libgtk2.0-dev \
        pkg-config \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libtbb-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libdc1394-dev \
        python3-dev \
        unzip \
        wget && \
    rm -rf /var/lib/apt/lists/*


# Install rtabmap and the stereo image processing package (note that the rtabmap installation was moved here for testing purposes 18/09-2025)
RUN apt-get update && \ 
    apt install ros-${ROS_DISTRO}-rtabmap-ros -y && \
    apt-get install ros-${ROS_DISTRO}-stereo-image-proc -y && \
    rm -rf /var/lib/apt/lists/*

# Install ultralytics and opencv-python
RUN apt-get update && apt-get install -y python3-opencv


COPY src/ src/

RUN find src/ -path "*/scripts/*" -type f -exec chmod +x {} \;

RUN git clone --recurse-submodules -b humble-v4.1.4 \
    https://github.com/stereolabs/zed-ros2-wrapper.git \
    src/zed-ros2-wrapper

# Insert common.yaml
RUN cd src/zed-ros2-wrapper && \
    cp -r ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}/src/rover/slam/config/common.yaml zed_wrapper/config/common.yaml

RUN apt-get update && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y && \
    rm -rf /var/lib/apt/lists/*

# interfaces probe_detection
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && \
colcon build --parallel-workers $(nproc) --symlink-install \
    --event-handlers console_direct+ --base-paths src \
    --packages-ignore navigation manipulator rover gorm_base_control gorm_navigation gorm_teleop gorm_web_interface \
    --packages-select zed_interfaces zed_components zed_wrapper \ 
    --cmake-args \
        ' -DCMAKE_BUILD_TYPE=Release' \
        ' -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-12.6' \
        ' -DCMAKE_LIBRARY_PATH=/usr/local/cuda-12.6/lib64/stubs:/usr/lib/aarch64-linux-gnu' \
        ' -DCMAKE_CXX_FLAGS=\"-Wl,--allow-shlib-undefined\"' \
        ' -DTENSORRT_INCLUDE_DIR=/usr/include/aarch64-linux-gnu' \
        ' --no-warn-unused-cli'"

ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && bash"] 
#, "source ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}/install/setup.bash && exec \"$@\"", "bash"]