# Replace the base image with the new one
FROM dustynv/l4t-pytorch:r36.4.0

ARG ROS_DISTRO=humble
ARG BASE_FOLDER=/root/orin
ARG ROS_WORKSPACE_NAME=ERC-Mars-Rover
ARG ZED_WORKSPACE_NAME=ros2_zed_ws

ARG ZED_SDK_MAJOR=4
ARG ZED_SDK_MINOR=2
ARG ZED_SDK_PATCH=5
ARG L4T_MAJOR=36
ARG L4T_MINOR=4

ARG DEBIAN_FRONTEND=noninteractive

# KEEP: Install additional system packages not necessarily in the base image
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    libopenblas-dev \
    libopenmpi-dev \
    openmpi-bin \
    openmpi-common \
    gfortran \
    nano \
    libomp-dev && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Install setuptools, Cython, wheel, and colcon-common-extensions from standard PyPI
RUN pip3 install --no-cache-dir --index-url https://pypi.org/simple setuptools Cython wheel colcon-common-extensions

###################################
###     Install cuSPARSELt      ###
###################################

# cuSPARSELt
ARG cuSPARSELt_URL=https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb
ARG cuSPARSELt_DEB=cuda-keyring_1.1-1_all.deb

RUN wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certificate ${cuSPARSELt_URL} -O ${cuSPARSELt_DEB} && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    rm ${cuSPARSELt_DEB} && \
    apt-get update && \
    apt-get -y install libcusparselt0 libcusparselt-dev


###################################
###         Install ROS         ###
###################################

# KEEP: ROS is not included in the base image
RUN apt-get update && apt-get install -y locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV PYTHONIOENCODING=utf-8

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

RUN apt install software-properties-common -y && \
    add-apt-repository universe
    
RUN apt update && apt install curl -y && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" > /etc/apt/sources.list.d/ros2.list

RUN apt update && apt upgrade -y && \
    apt install ros-humble-desktop -y

#Additional utilities and tools
RUN apt-get update && apt-get install nano && apt-get install iputils-ping
RUN apt-get install busybox && apt-get install iproute2 -y
RUN apt-get install -y --no-install-recommends zstd wget less cmake curl gnupg2 \
    build-essential python3 python3-pip python3-dev python3-setuptools libusb-1.0-0-dev -y 
RUN apt-get install libspnav-dev -y && \
    apt-get install libbluetooth-dev -y && \
    apt-get install libcwiid-dev -y
RUN apt-get install git -y && \
    apt-get install python3-rosdep2 -y
RUN apt-get install kmod

# Check for pre-installed pip packages and install only what's missing
RUN pip3 install --no-cache-dir --index-url https://pypi.org/simple \
    grpcio==1.58.0 \
    skrl==1.3.0 \
    Jetson.GPIO \
    onnx \
    numpy\<2 \
    protobuf \
    requests \
    empy==3.3.4

# ZED SDK installation
RUN /bin/bash -c 'echo "# R${L4T_MAJOR} (release), REVISION: ${L4T_MINOR}" > /etc/nv_tegra_release && \
   apt-get update -y || true && \
   wget -q --no-check-certificate -O ZED_SDK_Linux_JP.run \
   https://download.stereolabs.com/zedsdk/${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}/l4t${L4T_MAJOR}.${L4T_MINOR}/jetsons && \
   chmod +x ZED_SDK_Linux_JP.run && ./ZED_SDK_Linux_JP.run -- silent skip_tools && \
   rm -rf /usr/local/zed/resources/* && \
   rm -rf ZED_SDK_Linux_JP.run && \
   rm -rf /var/lib/apt/lists/*'

# Run ZED SDK Python API installer with standard PyPI index
RUN PIP_INDEX_URL=https://pypi.org/simple python3 /usr/local/zed/get_python_api.py

RUN ln -sf /usr/lib/aarch64-linux-gnu/tegra/libv4l2.so.0 /usr/lib/aarch64-linux-gnu/libv4l2.so

# ROS dependencies
RUN apt-get update && \
    rosdep update && \
    apt-get install -y ros-humble-zed-msgs ros-humble-nmea-msgs ros-humble-geographic-msgs ros-humble-image-transport ros-humble-cob-srvs ros-humble-diagnostic-updater ros-humble-robot-localization ros-humble-point-cloud-transport ros-humble-xacro && \
    rm -rf /var/lib/apt/lists/*

# TensorRT (may not be fully pre-installed)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libnvinfer-dev \
    libnvinfer-plugin-dev \
    libnvinfer-bin \
    tensorrt && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Cyclone DDS
RUN apt-get update && apt-get install -y ros-humble-rmw-cyclonedds-cpp && rm -rf /var/lib/apt/lists/*
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

# ROS environment setup
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc